main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.header, name='header'),
    path('user_info/', views.user_info, name='user_info'),
]

main/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=150)


    def __str__(self):
        return self.name


class Film(models.Model):
    title = models.CharField(max_length=200)
    year = models.PositiveIntegerField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create forms here 

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)


    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit: 
            user.save()
        return user

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home (request):
    return render(request, 'home.html')


def header(request):
    title = 'Main Page'

    return render(request, 
        'main/header.html',
        {'title':title})

def user_info(request):
    userinfo = {
        'username': 'Kiprotich',
        'country': 'Kenya',
    }

    context = {
        'userinfo': userinfo,
        'title': 'User Info Page'
    }

    return render(request, 
        'main/user_info.html',
        context)

main/templates/main/header.html
{% extends 'base.html' %}
{% block content %}

<h1>This is the films main page</h1>
<!-- <h3>Link to the website pages:</h3>
<ul>
    <li><a href="{% url 'home' %}">Home Page</a></li>
    <li><a href="{% url 'main:header' %}">Main Page</a></li>
    <li><a href="{% url 'main:user_info'%}">User Info</a></li>
</ul> -->

{% endblock %}

main/templates/main/user_info.html
{% extends 'base.html' %}

{% block content %}

<h1>This is the user's info page.</h1>
<p>Usernam: Username</p>
<!-- <h3>Link to the websites pages:</h3>
<ul>
    <li><a href="{% url 'home'%}"> Home Page</a></li>
    <li><a href="{% url 'main:header'%}">Main Page</a></li>
    <li><a href="{% url 'main:user_info'%}">User Info</a></li>
</ul> -->

{% endblock %}